package tsnode

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"

	"github.com/ipfs/boxo/ipns"
	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/peer"
)

// A browser web client signs its own IPNS records (playlist publish/renew) — it has no Go
// keystore to delegate to. That makes JS->Go record compatibility a trust-boundary contract,
// not an implementation detail: if a JS-signed V2 record doesn't validate here, browser
// playlist authoring is impossible.
//
// testdata/ipns_js_record.json is generated by the `ipns` npm package (see the web client's
// key/record code) and is checked in as a frozen vector, exactly like the TS-generated FLAC
// vectors the Rust side asserts against. Regenerate it only alongside a deliberate change to
// how the browser signs.
func TestIPNSRecordFromJSValidates(t *testing.T) {
	var fx struct {
		Name      string `json:"name"`
		Value     string `json:"value"`
		Sequence  uint64 `json:"sequence"`
		RecordB64 string `json:"recordB64"`
	}
	raw, err := os.ReadFile("testdata/ipns_js_record.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	rec, err := base64.StdEncoding.DecodeString(fx.RecordB64)
	if err != nil {
		t.Fatalf("fixture record not base64: %v", err)
	}

	// Exactly the path ingestGossip takes for an untrusted record off the topic.
	pid, err := peer.Decode(fx.Name)
	if err != nil {
		t.Fatalf("decode name %q: %v", fx.Name, err)
	}
	got, err := ipns.UnmarshalRecord(rec)
	if err != nil {
		t.Fatalf("unmarshal JS-signed record: %v", err)
	}
	if err := ipns.ValidateWithName(got, ipns.NameFromPeer(pid)); err != nil {
		t.Fatalf("JS-signed record failed Go validation: %v", err)
	}

	seq, err := got.Sequence()
	if err != nil {
		t.Fatalf("sequence: %v", err)
	}
	if seq != fx.Sequence {
		t.Errorf("sequence = %d, want %d", seq, fx.Sequence)
	}
	val, err := got.Value()
	if err != nil {
		t.Fatalf("value: %v", err)
	}
	if val.String() != fx.Value {
		t.Errorf("value = %q, want %q", val, fx.Value)
	}
}

// Browser storage is evictable: if IndexedDB is cleared, every playlist key the user owns is
// gone and those playlists can never be updated, republished, or tombstoned again. The mitigation
// is key export/import — which only works if the browser writes the SAME protobuf encoding
// loadOrCreateKey/ImportIdentity read. Prove it: a JS-exported key must unmarshal here and yield
// the same PeerId (i.e. the same playlist identity) it had in the browser.
func TestPrivateKeyFromJSImportsAndMatchesName(t *testing.T) {
	var fx struct {
		Name               string `json:"name"`
		PrivKeyProtobufB64 string `json:"privKeyProtobufB64"`
	}
	raw, err := os.ReadFile("testdata/ipns_js_record.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	keyBytes, err := base64.StdEncoding.DecodeString(fx.PrivKeyProtobufB64)
	if err != nil {
		t.Fatalf("fixture key not base64: %v", err)
	}
	priv, err := crypto.UnmarshalPrivateKey(keyBytes)
	if err != nil {
		t.Fatalf("JS-exported key failed Go unmarshal (export/import is broken): %v", err)
	}
	pid, err := peer.IDFromPrivateKey(priv)
	if err != nil {
		t.Fatalf("peer id from key: %v", err)
	}
	if pid.String() != fx.Name {
		t.Errorf("imported key yields PeerId %s, want %s — the playlist identity did not survive export",
			pid, fx.Name)
	}
}

// A record signed by one key must NOT validate under a different name — the property the
// gossip topic's untrusted-input handling depends on.
func TestIPNSRecordFromJSRejectsWrongName(t *testing.T) {
	var fx struct {
		RecordB64 string `json:"recordB64"`
	}
	raw, err := os.ReadFile("testdata/ipns_js_record.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	rec, err := base64.StdEncoding.DecodeString(fx.RecordB64)
	if err != nil {
		t.Fatalf("fixture record not base64: %v", err)
	}
	got, err := ipns.UnmarshalRecord(rec)
	if err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	// The prod catalog publisher key — a valid name, but not this record's signer.
	other, err := peer.Decode("12D3KooWDb53qFZvANj5kDCr3riMhT2HJG32i5xqFKhvBtzh7wPC")
	if err != nil {
		t.Fatalf("decode other name: %v", err)
	}
	if err := ipns.ValidateWithName(got, ipns.NameFromPeer(other)); err == nil {
		t.Fatal("JS-signed record validated under the WRONG name — signature check is not binding")
	}
}
