package tsnode

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
)

// The web client publishes playlists by emitting ONE gossipsub message — the doc travels inline
// next to its signed IPNS record, so nobody ever dials the author and a browser (which cannot be
// dialled) is a first-class publisher. That makes the envelope a cross-implementation contract: if
// a JS-built envelope does not validate here, a playlist made in a browser is invisible to every
// desktop, silently.
//
// testdata/playlist_js_envelope.json is generated by @trackerstream/playlists-web's own
// encodePlaylistMsg + IPNS signing, and checked in frozen. Regenerate it only alongside a
// deliberate change to how the browser publishes.
func loadJSEnvelope(t *testing.T) (name string, seq uint64, envelope, linkEnvelope, rec, doc []byte) {
	t.Helper()
	var fx struct {
		Name            string `json:"name"`
		Seq             uint64 `json:"seq"`
		DocB64          string `json:"docB64"`
		RecordB64       string `json:"recordB64"`
		EnvelopeB64     string `json:"envelopeB64"`
		LinkEnvelopeB64 string `json:"linkEnvelopeB64"`
	}
	raw, err := os.ReadFile("testdata/playlist_js_envelope.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	dec := func(s string) []byte {
		b, err := base64.StdEncoding.DecodeString(s)
		if err != nil {
			t.Fatalf("fixture field not base64: %v", err)
		}
		return b
	}
	return fx.Name, fx.Seq, dec(fx.EnvelopeB64), dec(fx.LinkEnvelopeB64), dec(fx.RecordB64), dec(fx.DocB64)
}

func TestPlaylistEnvelopeFromJSValidates(t *testing.T) {
	wantName, wantSeq, envelope, _, wantRec, wantDoc := loadJSEnvelope(t)

	name, rec, doc, err := decodePlaylistMsg(envelope)
	if err != nil {
		t.Fatalf("decode JS envelope: %v", err)
	}
	if name != wantName {
		t.Errorf("name = %q, want %q", name, wantName)
	}
	if string(rec) != string(wantRec) {
		t.Error("record frame did not survive the JS -> Go boundary")
	}
	if string(doc) != string(wantDoc) {
		t.Error("doc frame did not survive the JS -> Go boundary")
	}

	// The whole trust story: signature + EOL + the doc hashing to the CID the record signed over.
	seq, err := validatePlaylistMsg(name, rec, doc)
	if err != nil {
		t.Fatalf("JS-published playlist failed Go validation: %v", err)
	}
	if seq != wantSeq {
		t.Errorf("sequence = %d, want %d", seq, wantSeq)
	}
}

// The doc is unsigned; only the record is. What binds them is that the doc must hash to the CID
// inside the record. Flip one byte of the doc and validation MUST fail — otherwise anyone could
// staple any playlist onto a valid record and it would ride the mesh under someone else's name.
func TestPlaylistEnvelopeFromJSRejectsTamperedDoc(t *testing.T) {
	name, _, _, _, rec, doc := loadJSEnvelope(t)

	tampered := make([]byte, len(doc))
	copy(tampered, doc)
	tampered[len(tampered)/2] ^= 0x01

	if _, err := validatePlaylistMsg(name, rec, tampered); err == nil {
		t.Fatal("a tampered doc validated — the doc is not bound to its record's CID")
	}
}

// A record signed by one key must not validate under another name.
func TestPlaylistEnvelopeFromJSRejectsWrongName(t *testing.T) {
	_, _, _, _, rec, doc := loadJSEnvelope(t)
	const other = "12D3KooWDb53qFZvANj5kDCr3riMhT2HJG32i5xqFKhvBtzh7wPC"
	if _, err := validatePlaylistMsg(other, rec, doc); err == nil {
		t.Fatal("a JS-published playlist validated under the WRONG name")
	}
}
