// Kubo-free oracle for CI: build the CID-DAG for each bundled fixture, reassemble
// it from an in-memory BlockGetter (a Map of cid->bytes taken straight from
// dag.blocks — NO kubo, no network), and assert:
//   1. byte-identity      — reassembled bytes === original fixture bytes
//   2. CID verification    — reassemble runs with { verify: true }, so a tampered
//                            block would throw (also exercised explicitly below)
//   3. cross-module dedup  — a sample whose PCM is byte-identical across two
//                            fixtures collapses to a SHARED chunk + pcm-root CID
//   4. tamper rejection    — flipping a byte in a chunk block is caught by the
//                            CID check during reassembly
//
// The fixtures are deterministically generated by ./fixtures/gen-fixtures.mjs
// (tiny, structurally-valid, copyright-free modules) — see that file. This test
// needs ONLY this package's source; it is the spine of the CI pipeline.
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { CID } from "multiformats/cid";
import { buildDag, reassemble } from "../src/dag.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIX = join(HERE, "fixtures");

const FIXTURES = ["fixture-a.mod", "fixture-b.mod", "fixture.it"];

// Sanity: the fixtures must be present. If missing, fail loudly with the fix.
for (const f of FIXTURES) {
  if (!existsSync(join(FIX, f))) {
    console.error(
      `MISSING fixture ${f} — run \`node packages/repack/test/fixtures/gen-fixtures.mjs\` to (re)generate.`,
    );
    process.exit(1);
  }
}

let allOk = true;
const fail = (msg: string) => {
  allOk = false;
  console.log(`FAIL ${msg}`);
};

// Shared in-memory block store across all fixtures => cross-module dedup is
// visible as blocks colliding on the same CID key.
const store = new Map<string, Uint8Array>();
const get = async (cid: CID): Promise<Uint8Array> => {
  const b = store.get(cid.toString());
  if (!b) throw new Error(`missing block ${cid}`);
  return b;
};

const dags: { name: string; root: CID; pcmRoots: string[] }[] = [];
let summedBlocks = 0;

for (const name of FIXTURES) {
  const orig = new Uint8Array(readFileSync(join(FIX, name)));
  const dag = await buildDag(orig);
  for (const blk of dag.blocks) {
    summedBlocks++;
    store.set(blk.cid.toString(), blk.bytes);
  }

  const { bytes } = await reassemble(dag.root, get, { verify: true });
  const equal = bytes.length === orig.length && Buffer.compare(bytes, orig) === 0;
  if (equal) {
    console.log(
      `OK   ${name}  ${orig.length}B  samples=${dag.stats.numSamples}  chunks=${dag.stats.numChunks}  root=${dag.root.toString().slice(0, 12)}…`,
    );
  } else {
    fail(`${name} reassembly is NOT byte-identical (len ${bytes.length} vs ${orig.length})`);
  }

  dags.push({
    name,
    root: dag.root,
    pcmRoots: dag.manifest.samples.map((s) => s.pcmRoot.toString()),
  });
}

// --- Cross-module dedup oracle ---------------------------------------------
// fixture-a.mod and fixture-b.mod share their FIRST sample's PCM (and fixture.it
// shares it as its SECOND sample). So that sample's pcm-root CID must be IDENTICAL
// across all three, and the union of all blocks must be strictly smaller than the
// naive sum (the shared chunk + pcm-root are stored once).
{
  const a = dags.find((d) => d.name === "fixture-a.mod")!;
  const b = dags.find((d) => d.name === "fixture-b.mod")!;
  const it = dags.find((d) => d.name === "fixture.it")!;
  const sharedAB = a.pcmRoots[0] === b.pcmRoots[0];
  const sharedIT = it.pcmRoots.includes(a.pcmRoots[0]);
  if (sharedAB && sharedIT) {
    console.log(`OK   dedup: shared sample pcm-root CID identical across a/b/it (${a.pcmRoots[0].slice(0, 16)}…)`);
  } else {
    fail(`dedup: shared sample pcm-root CID differs (a==b:${sharedAB} it-has-shared:${sharedIT})`);
  }

  const deduped = summedBlocks - store.size;
  if (deduped > 0) {
    console.log(`OK   dedup: ${summedBlocks} blocks across fixtures collapse to ${store.size} unique (-${deduped})`);
  } else {
    fail(`dedup: expected shared blocks but union (${store.size}) == sum (${summedBlocks})`);
  }
}

// --- Tamper rejection -------------------------------------------------------
// Reassembly verifies every block against its CID. Flip a byte in the largest
// chunk and confirm reassemble throws (a corrupted/poisoned peer block is caught).
{
  const orig = new Uint8Array(readFileSync(join(FIX, "fixture-a.mod")));
  const dag = await buildDag(orig);
  let victim: string | null = null;
  let max = -1;
  for (const blk of dag.blocks) {
    if (blk.bytes.length > max) {
      max = blk.bytes.length;
      victim = blk.cid.toString();
    }
  }
  const tampered = new Map(store);
  const bad = Uint8Array.from(tampered.get(victim!)!);
  bad[0] ^= 0xff;
  tampered.set(victim!, bad);

  let caught = false;
  try {
    await reassemble(dag.root, async (cid) => tampered.get(cid.toString())!, { verify: true });
  } catch {
    caught = true;
  }
  if (caught) console.log(`OK   tamper: corrupted chunk block rejected by CID verification`);
  else fail(`tamper: corrupted block ACCEPTED (CID verification did not fire)`);
}

console.log(`\n${allOk ? "PASS" : "FAIL"}  ${store.size} unique blocks in shared store`);
process.exit(allOk ? 0 : 1);
